import type { Metadata } from 'next';
import localFont from 'next/font/local';

import AntdRegistry from '@/lib/AntdRegistry';

import LanguageSwitcher from '@/components/LanguageSwitcher';
import Loading from '@/components/Loading';

import 'antd/dist/reset.css';

import '@/app/styles/globals.scss';
import styles from './styles/page.module.scss';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <main>
          <AntdRegistry>
            <Loading>
              <div className={styles.languageSwitcher}>
                <LanguageSwitcher />
              </div>
              {children}
            </Loading>
          </AntdRegistry>
        </main>
      </body>
    </html>
  );
}
